FROM mcr.microsoft.com/windows/nanoserver@sha256:7ca8e6965a57e9f6ec12910217cca7c4bb6a15430beb3e96967bae9542b2209c

LABEL io.buildpacks.buildpackage.metadata="{\"id\": \"samples/baselayer-windows\", \"version\": \"0.0.1\", \"stacks\": [{\"id\": \"io.buildpacks.samples.stacks.nanoserver-1809\"}]}"
LABEL io.buildpacks.buildpack.layers="{\"samples/baselayer-windows\":{\"0.0.1\":{\"api\":\"0.2\",\"stacks\":[{\"id\":\"io.buildpacks.samples.stacks.nanoserver-1809\"}],\"layerDiffID\":\"sha256:0d17f39b36faac55a085f9fefcea752014c4b0387533bb47fbd77661adf5e1f6\",\"homepage\":\"https://github.com/buildpacks/samples\"}}}"
